
@host = 127.0.0.1:8000
@prefix=api/v1

@token=replace-with-token

GET http://{{host}}/{{prefix}}/documents
Authorization: Bearer {{token}}

### 
POST http://{{host}}/{{prefix}}/documents
Authorization: Bearer {{token}}
Content-Type: multipart/form-data;boundary=file1

--file1
Content-Disposition: form-data; name="file"; filename="progress.md"
Content-Type: text/markdown

< ./docs/progress.md

--file1--




###
GET http://{{host}}/{{prefix}}/test
Authorization: Bearer {{token}}


### index
POST http://{{host}}/{{prefix}}/documents/01a08f47-6c5e-71b6-91c1-5f63ba79288b/index
Authorization: Bearer {{token}}
Content-Type: application/json


### 查询
POST http://{{host}}/{{prefix}}/search
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "query": "保存",
    "limit": 5
}
